* Lucien Cartier-Tilet
Actuellement étudiant en Master Informatique à l’Université Vincennes-Saint-Denis après y avoir obtenu mon diplôme en Licence d’Informatique. Je fus également directeur technique chez VoxWave, et y ai développé la première chanteuse virtuelle francophone durant les six années passées dans cette entreprise que j’ai co-fondé.

De nationalité française, je parle couramment Anglais et j’ai des bases en Espagnol, en Japonais et en Lingua Franca Nova (Elefen) ; j’apprends actuellement également à parler en Norvégien (Bokmål). Mes centres d’intérêt sont variés, allant de la programmation à la linguistique en passant par la création d’univers fictifs.

** Contact
- téléphone :: +33(0)6.83.90.56.89
- email :: [[mailto:lucien@phundrak.com][lucien@phundrak.com]]

** Expériences Professionnelles
*** VoxWave SAS - Directeur Technique
De la fondation du projet (Septembre 2012), création de l’entreprise en Octobre 2014, jusqu’au 31 Juillet 2018.
- Co-fondateur
- Programmation de voix de chant de synthèse
- R&D linguistiques
- Support utilisateur
- Formation de recrues au développement de chanteurs virtuels.

*** Université Paris 8 - Tuteur
De Septembre 2018 à Mai 2019 et de Septembre 2020 à Mai 2021.
- Accueil d’étudiants en début d’année
- Accompagnement et soutient aux étudiants

** Éducation
*** Master d’Informatique (en cours) - Université Paris 8
De Septembre 2020 à Mai 2022. Volonté de poursuivre en doctorat.

*** Licence d’Informatique - Université Paris 8
Septembre 2016 à Mai 2019
- Mention Bien

*** Baccalauréat - Lycée de la Plaine de l’Ain
Septembre 2010 à Juillet 2013
- Baccalauréat série S, spécialisation Sciences de l’Ingénieur
- Mention Bien

** Compétences

*** Programmation
- Notions :: Prolog, Scheme
- Connaissances :: Python, Rust, HTML, CSS, JavaScript (EcmaScript 6), shell UNIX (bash, fish, Eshell), EmacsLisp, Dart
- Connaissances solides :: C, C++

*** Outils de développement
- Emacs (outil principal, incluant org-mode), Vim
- Git (dont Magit)
- Nginx, Caddyserver
- Docker, Docker Compose

*** Systèmes d’exploitation
- Utilisation et administration GNU/Linux (Arch Linux, Void Linux, Debian, Ubuntu, Pop!_OS)
- Connaissance basique de Guix (incluant GuixSD)
- Administration de serveurs web et serveurs de stockage GNU/Linux (Arch Linux, Debian)
  - Sur VPS et sur machines locales
- Utilisation Windows (de XP à 10, excepté Vista)

*** Bureautique
- org-mode (outil principal), LaTeX
- Libre Office, Microsoft Office, WPS Office, suite Google (Docs, Sheets)

*** Synthèse vocale de chant
- Création et développement de banques vocales
  - VOCALOID3
  - Alter/Ego
  - Chipspeech
  - UTAU
- Utilisation de VOCALOID2 à VOCALOID4, Alter/Ego, Chipspeech, UTAU, CeVIO Creative Studio

*** Ingénieurie son
- FL Studio (10 à 20)
- iZotope RX (3 à 6)
- T-RackS CS

** Activités
*** Association Supran - Vice-Président
Depuis Mars 2020
- Association loi 1901 promouvant ses artistes-membres via son réseau tout en les encourageant à collaborer entre eux
- Webmestre du collectif
- Directeur Artistique VSU

*** Activités personnelles
*** Écriture
Écriture d’un roman et de nouvelles dans un univers fantasy personnel

*** Création d’idéolangues (langues construites)
  - Langues /a priori/ (créées /ex nihilo/)
    - Proto-Ñyqy
    - Proto-Tãso
  - Langues /a posteriori/ (créées à partir de langues existantes)
    - Eittlandais, descendant du Vieux Norrois
    - Mauge, descendant du Proto-Italique

*** Création d’univers fictifs
  - Eittlande, pays nordique fictif existant dans notre univers
  - Univers fantasy original
  - Direction artistique de la création d’un univers participatif magicpink victorien

*** Musique
- Pratique occasionnelle de la guitare sèche
- Mixage de musique, réparation et nettoyage audio
